2015-12-21 00:18:02 Run_Script_Main     INFO     ResCons begins!
2015-12-21 00:18:02 Run_Script_Main     INFO     ResCon will run in 'Protein mode' as user has requested.
2015-12-21 00:18:02 Run_Script_Main     INFO     'Reference file provided by user: 
	C:/Users/Mana_Dell/Desktop/test/test2/Template_Ecoli_IPPase.fasta
2015-12-21 00:18:02 Run_Script_Main     ERROR    Error that resulted when creating path "C:/Users/Mana_Dell/Desktop/test/test2/Output/":
  [Error 183] Cannot create a file when that file already exists: 'C:/Users/Mana_Dell/Desktop/test/test2/Output/'
2015-12-21 00:18:02 Run_Script_Main     WARNING  Folder "C:/Users/Mana_Dell/Desktop/test/test2/Output/" already exists. All or some files in it may get overwritten by ResCons. Do you wish to continue?
2015-12-21 00:18:03 Run_Script_Main     INFO     User has selected (True = Yes, False = No):  True
2015-12-21 00:18:03 Run_Script_Main     INFO     ResCons will continue as user has requested.
2015-12-21 00:18:03 Run_Script_Main     INFO     Output folder path provided by user: C:/Users/Mana_Dell/Desktop/test/test2/Output/
2015-12-21 00:18:03 Clustal_Alignment   INFO     Pre-Aligned file was provided by user.
2015-12-21 00:18:03 Clustal_Alignment   INFO     Pre-Aligned file provided: 
	C:/Users/Mana_Dell/Desktop/test/test2/Small_Ecoli_Trimmed_95perc_threshold_Matches only_Clade 1.0365.fasta.
2015-12-21 00:18:03 GUI_Main            INFO     All output files will be stored at: 
	C:/Users/Mana_Dell/Desktop/test/test2/Output/.
2015-12-21 00:18:03 Run_Script_Main     INFO     All residue positions entered are less than the length of reference sequence.
2015-12-21 00:18:03 Fetch_Mismatch      INFO     Alignment format is detected as "fasta" format
2015-12-21 00:18:03 Fetch_Mismatch      ERROR    Error: Alignment file "C:/Users/Mana_Dell/Desktop/test/test2/Small_Ecoli_Trimmed_95perc_threshold_Matches only_Clade 1.0365.fasta" does not have Sequence ID corresponding to your reference sequence. Fix it and try again!
2015-12-21 00:18:09 User_error          ERROR    Resulted in an error that can be corrected by User. ResCon is ready for next job now!
2015-12-21 00:18:09 User_error          ERROR    Error that resulted: Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "C:/Users/Mana_Dell/Dropbox/ResCons/Ver25_ResCon.py", line 3231, in run_script
    fetch_mismatch()
  File "C:/Users/Mana_Dell/Dropbox/ResCons/Ver25_ResCon.py", line 873, in fetch_mismatch
    raise_enabler('stop')
  File "C:/Users/Mana_Dell/Dropbox/ResCons/Ver25_ResCon.py", line 468, in raise_enabler
    raise Exception("Error can be rectified by user (you)!. Controlled termination by ResCon!")
Exception: Error can be rectified by user (you)!. Controlled termination by ResCon!


